export const FMCG_PRODUCTS = [
    // Flours & Grains
    { id: 'fl-1', name: 'Jogoo Maize Meal 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Jogoo' },
    { id: 'fl-2', name: 'Jogoo Maize Meal 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Jogoo' },
    { id: 'fl-3', name: 'Soko Maize Meal 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Soko' },
    { id: 'fl-4', name: 'Pembe Maize Meal 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Pembe' },
    { id: 'fl-5', name: 'Hostess Maize Meal 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Hostess' },
    { id: 'fl-6', name: 'Ajab Wheat Flour 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Ajab' },
    { id: 'fl-7', name: 'Exe Wheat Flour 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Exe' },
    { id: 'fl-8', name: 'Dola Wheat Flour 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Dola' },
    { id: 'fl-9', name: 'Norda Wheat Flour 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Norda' },

    // Sugar & Sweeteners
    { id: 'sg-1', name: 'Kabras Sugar 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Kabras' },
    { id: 'sg-2', name: 'Kabras Sugar 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Kabras' },
    { id: 'sg-3', name: 'Nutrameal Sugar 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Nutrameal' },
    { id: 'sg-4', name: 'Mara Sugar 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Mara' },

    // Cooking Oils & Fats
    { id: 'oil-1', name: 'Fresh Fri Cooking Oil 1L', category: 'Pantry', image: 'https://placehold.co/100x100?text=FreshFri' },
    { id: 'oil-2', name: 'Fresh Fri Cooking Oil 2L', category: 'Pantry', image: 'https://placehold.co/100x100?text=FreshFri' },
    { id: 'oil-3', name: 'Fresh Fri Cooking Oil 3L', category: 'Pantry', image: 'https://placehold.co/100x100?text=FreshFri' },
    { id: 'oil-4', name: 'Rina Cooking Oil 1L', category: 'Pantry', image: 'https://placehold.co/100x100?text=Rina' },
    { id: 'oil-5', name: 'Rina Cooking Oil 2L', category: 'Pantry', image: 'https://placehold.co/100x100?text=Rina' },
    { id: 'oil-6', name: 'Golden Fry Cooking Oil 2L', category: 'Pantry', image: 'https://placehold.co/100x100?text=GoldenFry' },
    { id: 'oil-7', name: 'Kasuku Cooking Fat 500g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Kasuku' },
    { id: 'oil-8', name: 'Kasuku Cooking Fat 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Kasuku' },

    // Dairy
    { id: 'dr-1', name: 'Brookside Dairy Fresh Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Brookside' },
    { id: 'dr-2', name: 'KCC Gold Crown Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=KCC' },
    { id: 'dr-3', name: 'Fresha Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Fresha' },
    { id: 'dr-4', name: 'Mount Kenya Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=MtKenya' },
    { id: 'dr-5', name: 'Bio Yoghurt Strawberry 150ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Bio' },
    { id: 'dr-6', name: 'Bio Yoghurt Vanilla 150ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Bio' },
    { id: 'dr-7', name: 'Delamere Yoghurt 250ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Delamere' },
    { id: 'dr-8', name: 'Prestige Margarine 500g', category: 'Dairy', image: 'https://placehold.co/100x100?text=Prestige' },
    { id: 'dr-9', name: 'Blue Band Margarine 500g', category: 'Dairy', image: 'https://placehold.co/100x100?text=BlueBand' },

    // Beverages
    { id: 'bev-1', name: 'Ketepa Pride Tea Leaves 500g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Ketepa' },
    { id: 'bev-2', name: 'Kericho Gold Tea Bags 50pc', category: 'Beverages', image: 'https://placehold.co/100x100?text=KerichoGold' },
    { id: 'bev-3', name: 'Nescafe Classic Coffee 50g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Nescafe' },
    { id: 'bev-4', name: 'Dormans Instant Coffee 100g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Dormans' },
    { id: 'bev-5', name: 'Milo Energy Drink 400g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Milo' },
    { id: 'bev-6', name: 'Coca Cola Soda 1.25L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Coke' },
    { id: 'bev-7', name: 'Fanta Orange Soda 1.25L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Fanta' },
    { id: 'bev-8', name: 'Keringet Drinking Water 1L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Keringet' },

    // Personal Care
    { id: 'pc-1', name: 'Geisha Soap Aloe Vera 200g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Geisha' },
    { id: 'pc-2', name: 'Dettol Soap Original 175g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Dettol' },
    { id: 'pc-3', name: 'Colgate Herbal Toothpaste 140g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Colgate' },
    { id: 'pc-4', name: 'Aquafresh Toothpaste 140g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Aquafresh' },
    { id: 'pc-5', name: 'Nice & Lovely Body Lotion 200ml', category: 'Personal Care', image: 'https://placehold.co/100x100?text=NiceLovely' },
    { id: 'pc-6', name: 'Vaseline Petroleum Jelly 250g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Vaseline' },

    // Household & Cleaning
    { id: 'hh-1', name: 'Omo Washing Powder 500g', category: 'Household', image: 'https://placehold.co/100x100?text=Omo' },
    { id: 'hh-2', name: 'Sunlight Washing Powder 500g', category: 'Household', image: 'https://placehold.co/100x100?text=Sunlight' },
    { id: 'hh-3', name: 'Aerial Washing Powder 500g', category: 'Household', image: 'https://placehold.co/100x100?text=Aerial' },
    { id: 'hh-4', name: 'Vim Scouring Powder 500g', category: 'Household', image: 'https://placehold.co/100x100?text=Vim' },
    { id: 'hh-5', name: 'Jik Bleach Regular 750ml', category: 'Household', image: 'https://placehold.co/100x100?text=Jik' },
    { id: 'hh-6', name: 'Harpic Toilet Cleaner 500ml', category: 'Household', image: 'https://placehold.co/100x100?text=Harpic' },
    { id: 'hh-7', name: 'Menengai Bar Soap 1kg', category: 'Household', image: 'https://placehold.co/100x100?text=Menengai' },
    { id: 'hh-8', name: 'Whitestar Bar Soap 1kg', category: 'Household', image: 'https://placehold.co/100x100?text=Whitestar' },

    // Bakery
    { id: 'bk-1', name: 'Broadways White Bread 400g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Broadways' },
    { id: 'bk-2', name: 'Festive Bread 400g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Festive' },
    { id: 'bk-3', name: 'Super Loaf 400g', category: 'Snacks', image: 'https://placehold.co/100x100?text=SuperLoaf' },
    { id: 'bk-4', name: 'NuVita Biscuits 200g', category: 'Snacks', image: 'https://placehold.co/100x100?text=NuVita' },
    { id: 'bk-5', name: 'Digestive Biscuits 200g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Digestive' },

    // Scraped from Carrefour
    { id: 'cf-1', name: 'Royco Cube Fortified 4gx40', category: 'Pantry', image: 'https://placehold.co/100x100?text=Royco' },
    { id: 'cf-2', name: 'Knorr Cube Beef Chilli 8gx6', category: 'Pantry', image: 'https://placehold.co/100x100?text=Knorr' },
    { id: 'cf-3', name: 'Knorr Chicken Soft Cube 8gx6', category: 'Pantry', image: 'https://placehold.co/100x100?text=Knorr' },
    { id: 'cf-4', name: 'Kensalt Premium Iodated Table Salt 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Salt' },
    { id: 'cf-5', name: 'Tropical Heat Spices Paprika 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Spices' },
    { id: 'cf-6', name: 'Royco Mchuzi Mix Beef Sachet 170g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Royco' },
    { id: 'cf-7', name: 'Tropical Heat Spices Tea Masala 100G', category: 'Pantry', image: 'https://placehold.co/100x100?text=Masala' },
    { id: 'cf-8', name: 'Royco Chicken Cubes Fortified 40\'s', category: 'Pantry', image: 'https://placehold.co/100x100?text=Royco' },
    { id: 'cf-9', name: 'Tropical Heat Spices Pilau Masala Ground 100G', category: 'Pantry', image: 'https://placehold.co/100x100?text=Masala' },
    { id: 'cf-10', name: 'Tropical Heat Spices Garlic Powder 100G', category: 'Pantry', image: 'https://placehold.co/100x100?text=Garlic' },
    { id: 'cf-11', name: 'Simba Mbili Curry Powder 10g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Simba' },
    { id: 'cf-12', name: 'Tropical Heat Cumin Spice 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Cumin' },
    { id: 'cf-13', name: 'Tropical Heat Spices Black Pepper Ground 100G', category: 'Pantry', image: 'https://placehold.co/100x100?text=Pepper' },
    { id: 'cf-14', name: 'Red Bull Energy Drink 250ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=RedBull' },
    { id: 'cf-15', name: 'Pick N Peel Apple Juice 1L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Juice' },
    { id: 'cf-16', name: 'Quencher Life Premium Drinking Water 18L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Water' },
    { id: 'cf-17', name: 'Coca Cola Pet 2L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Coke' },
    { id: 'cf-18', name: 'Fanta Orange Pet 2L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Fanta' },
    { id: 'cf-19', name: 'Fanta Blackcurrant Pet 2L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Fanta' },
    { id: 'cf-20', name: 'Minute Maid Orange Pulpy Juice 1L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Juice' },
    { id: 'cf-21', name: 'Mayers Natural Spring Sparkling Water 1L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Water' },
    { id: 'cf-22', name: 'Coke Zero 2L Pet', category: 'Beverages', image: 'https://placehold.co/100x100?text=CokeZero' },
    { id: 'cf-23', name: 'Aquamist Mineral Water 10L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Water' },
    { id: 'cf-24', name: 'Sprite Pet 2L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Sprite' },
    { id: 'cf-25', name: 'Nescafe Classic Instant Coffee 200g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Nescafe' },
    { id: 'cf-26', name: 'Kericho Gold 100 Tea Bags 200G', category: 'Beverages', image: 'https://placehold.co/100x100?text=Tea' },
    { id: 'cf-27', name: 'Cadbury Drinking Chocolate Powder 450g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Choco' },
    { id: 'cf-28', name: 'Java Kenya AA Ground Coffee 375g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Java' },
    { id: 'cf-29', name: 'Pick N Peel Pineapple Juice 1L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Juice' },
    { id: 'cf-30', name: 'Kericho Gold Loose Black Tea 500g', category: 'Beverages', image: 'https://placehold.co/100x100?text=Tea' },

    // Rice & Pasta
    { id: 'rp-1', name: 'Pishori Rice 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Pishori' },
    { id: 'rp-2', name: 'Basmati Rice 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Basmati' },
    { id: 'rp-3', name: 'Mwea Rice 2kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Mwea' },
    { id: 'rp-4', name: 'Tilda Pure Basmati Rice 1kg', category: 'Pantry', image: 'https://placehold.co/100x100?text=Tilda' },
    { id: 'rp-5', name: 'Spaghetti 500g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Pasta' },
    { id: 'rp-6', name: 'Penne Pasta 500g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Pasta' },
    { id: 'rp-7', name: 'Macaroni 500g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Macaroni' },

    // Canned Goods & Preserves
    { id: 'cg-1', name: 'Cowboy Baked Beans 400g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Cowboy' },
    { id: 'cg-2', name: 'Del Monte Baked Beans 400g', category: 'Pantry', image: 'https://placehold.co/100x100?text=DelMonte' },
    { id: 'cg-3', name: 'StarKist Tuna in Brine 185g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Tuna' },
    { id: 'cg-4', name: 'Piller Corned Beef 300g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Piller' },
    { id: 'cg-5', name: 'Exeter Corned Beef 200g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Exeter' },
    { id: 'cg-6', name: 'Del Monte Whole Kernel Corn 340g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Corn' },
    { id: 'cg-7', name: 'Heinz Tomato Ketchup 500g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Heinz' },
    { id: 'cg-8', name: 'Del Monte Tomato Sauce 340g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Sauce' },
    { id: 'cg-9', name: 'Delmonte Chopped Tomatoes 400g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Tomato' },

    // Breakfast Cereals
    { id: 'bc-1', name: 'Weetabix Breakfast Cereal 430g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Weetabix' },
    { id: 'bc-2', name: 'Corn Flakes 500g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Cornflakes' },
    { id: 'bc-3', name: 'Kelloggs Frosties 500g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Frosties' },
    { id: 'bc-4', name: 'Quaker Oats 500g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Quaker' },
    { id: 'bc-5', name: 'Jungle Oats 500g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Jungle' },

    // Snacks & Confectionery
    { id: 'sn-1', name: 'Pringles Original 165g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Pringles' },
    { id: 'sn-2', name: 'Lays BBQ Chips 145g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Lays' },
    { id: 'sn-3', name: 'Tropical Heat Chevda Mix 200g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Chevda' },
    { id: 'sn-4', name: 'Cadbury Dairy Milk Chocolate 90g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Cadbury' },
    { id: 'sn-5', name: 'Galaxy Chocolate Bar 90g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Galaxy' },
    { id: 'sn-6', name: 'KitKat Chocolate 4 Finger 45g', category: 'Snacks', image: 'https://placehold.co/100x100?text=KitKat' },
    { id: 'sn-7', name: 'Mentos Mint Candies 37g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Mentos' },
    { id: 'sn-8', name: 'Orbit Gum Spearmint 14g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Orbit' },
    { id: 'sn-9', name: 'Snickers Chocolate Bar 50g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Snickers' },
    { id: 'sn-10', name: 'Twix Chocolate Bar 50g', category: 'Snacks', image: 'https://placehold.co/100x100?text=Twix' },

    // Baby Products
    { id: 'bp-1', name: 'Pampers Baby Dry Diapers Size 3 19pc', category: 'Baby Products', image: 'https://placehold.co/100x100?text=Pampers' },
    { id: 'bp-2', name: 'Huggies Dry Comfort Size 4 22pc', category: 'Baby Products', image: 'https://placehold.co/100x100?text=Huggies' },
    { id: 'bp-3', name: 'Cerelac Wheat 400g', category: 'Baby Products', image: 'https://placehold.co/100x100?text=Cerelac' },
    { id: 'bp-4', name: 'Nan 1 Infant Formula 400g', category: 'Baby Products', image: 'https://placehold.co/100x100?text=Nan' },
    { id: 'bp-5', name: 'Lactogen 1 Baby Formula 400g', category: 'Baby Products', image: 'https://placehold.co/100x100?text=Lactogen' },
    { id: 'bp-6', name: 'Johnsons Baby Wipes 56pc', category: 'Baby Products', image: 'https://placehold.co/100x100?text=Johnsons' },

    // More Dairy & Eggs
    { id: 'dr-10', name: 'Tuzo UHT Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Tuzo' },
    { id: 'dr-11', name: 'Daima Full Cream Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Daima' },
    { id: 'dr-12', name: 'Ilara Milk 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Ilara' },
    { id: 'dr-13', name: 'Mala Plain Yoghurt 500ml', category: 'Dairy', image: 'https://placehold.co/100x100?text=Mala' },
    { id: 'dr-14', name: 'Cheddar Cheese Block 200g', category: 'Dairy', image: 'https://placehold.co/100x100?text=Cheese' },
    { id: 'dr-15', name: 'Laughing Cow Cheese 8pc', category: 'Dairy', image: 'https://placehold.co/100x100?text=LaughingCow' },
    { id: 'dr-16', name: 'Fresh Eggs Tray 30pc', category: 'Dairy', image: 'https://placehold.co/100x100?text=Eggs' },
    { id: 'dr-17', name: 'Butter 500g', category: 'Dairy', image: 'https://placehold.co/100x100?text=Butter' },

    // Fresh Produce
    { id: 'fp-1', name: 'Fresh Tomatoes 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Tomatoes' },
    { id: 'fp-2', name: 'Fresh Onions 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Onions' },
    { id: 'fp-3', name: 'Potatoes 2kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Potatoes' },
    { id: 'fp-4', name: 'Carrots 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Carrots' },
    { id: 'fp-5', name: 'Cabbage Whole', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Cabbage' },
    { id: 'fp-6', name: 'Spinach Bunch', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Spinach' },
    { id: 'fp-7', name: 'Kale (Sukuma Wiki) Bunch', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Kale' },
    { id: 'fp-8', name: 'Bananas 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Bananas' },
    { id: 'fp-9', name: 'Oranges 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Oranges' },
    { id: 'fp-10', name: 'Apples 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Apples' },
    { id: 'fp-11', name: 'Mangoes 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Mangoes' },
    { id: 'fp-12', name: 'Watermelon Whole', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Watermelon' },
    { id: 'fp-13', name: 'Avocados 1kg', category: 'Fresh Produce', image: 'https://placehold.co/100x100?text=Avocados' },

    // More Cooking Ingredients
    { id: 'ci-1', name: 'Tropical Heat Cardamom Ground 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Cardamom' },
    { id: 'ci-2', name: 'Tropical Heat Cinnamon Ground 45g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Cinnamon' },
    { id: 'ci-3', name: 'Knorr Aromat Seasoning 70g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Aromat' },
    { id: 'ci-4', name: 'Tropical Heat Turmeric Ground 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Turmeric' },
    { id: 'ci-5', name: 'Tropical Heat Coriander Ground 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Coriander' },
    { id: 'ci-6', name: 'Mayonnaise 500ml', category: 'Pantry', image: 'https://placehold.co/100x100?text=Mayo' },
    { id: 'ci-7', name: 'Tomato Paste 70g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Paste' },
    { id: 'ci-8', name: 'Pilau Masala 50g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Masala' },
    { id: 'ci-9', name: 'Baking Powder 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Baking' },
    { id: 'ci-10', name: 'Baking Soda 100g', category: 'Pantry', image: 'https://placehold.co/100x100?text=Soda' },

    // More Beverages
    { id: 'bev-9', name: 'Tusker Lager Beer 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Tusker' },
    { id: 'bev-10', name: 'White Cap Beer 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=WhiteCap' },
    { id: 'bev-11', name: 'Pilsner Lager 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Pilsner' },
    { id: 'bev-12', name: 'Alvaro Drinking Water 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Alvaro' },
    { id: 'bev-13', name: 'Dasani Water 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Dasani' },
    { id: 'bev-14', name: 'Marathon Energy Drink 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Marathon' },
    { id: 'bev-15', name: 'Stoney Tangawizi Ginger Ale 300ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Stoney' },
    { id: 'bev-16', name: 'Novida Orange Drink 300ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Novida' },
    { id: 'bev-17', name: 'Del Monte Mango Juice 1L', category: 'Beverages', image: 'https://placehold.co/100x100?text=Mango' },
    { id: 'bev-18', name: 'Ribena Blackcurrant Juice 500ml', category: 'Beverages', image: 'https://placehold.co/100x100?text=Ribena' },

    // More Personal Care
    { id: 'pc-7', name: 'Palmolive Shower Gel 500ml', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Palmolive' },
    { id: 'pc-8', name: 'Lux Soap Soft Touch 175g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Lux' },
    { id: 'pc-9', name: 'Dove Beauty Bar 135g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Dove' },
    { id: 'pc-10', name: 'Imperial Leather Soap 125g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Imperial' },
    { id: 'pc-11', name: 'Closeup Toothpaste 125g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Closeup' },
    { id: 'pc-12', name: 'Oral B Toothpaste 125g', category: 'Personal Care', image: 'https://placehold.co/100x100?text=OralB' },
    { id: 'pc-13', name: 'Nivea Body Lotion 400ml', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Nivea' },
    { id: 'pc-14', name: 'Vaseline Body Lotion 400ml', category: 'Personal Care', image: 'https://placehold.co/100x100?text=VaselineL' },
    { id: 'pc-15', name: 'Sure Deodorant 150ml', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Sure' },
    { id: 'pc-16', name: 'Rexona Deodorant 150ml', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Rexona' },
    { id: 'pc-17', name: 'Always Sanitary Pads Normal 10pc', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Always' },
    { id: 'pc-18', name: 'Softcare Sanitary Pads 10pc', category: 'Personal Care', image: 'https://placehold.co/100x100?text=Softcare' },

    // More Household & Cleaning
    { id: 'hh-9', name: 'Ariel Washing Powder 1kg', category: 'Household', image: 'https://placehold.co/100x100?text=Ariel' },
    { id: 'hh-10', name: 'Persil Washing Powder 1kg', category: 'Household', image: 'https://placehold.co/100x100?text=Persil' },
    { id: 'hh-11', name: 'Downy Fabric Softener 900ml', category: 'Household', image: 'https://placehold.co/100x100?text=Downy' },
    { id: 'hh-12', name: 'Dettol Floor Cleaner 900ml', category: 'Household', image: 'https://placehold.co/100x100?text=DettolFlr' },
    { id: 'hh-13', name: 'Morning Fresh Dishwashing Liquid 400ml', category: 'Household', image: 'https://placehold.co/100x100?text=MorningFresh' },
    { id: 'hh-14', name: 'Finish Dishwasher Tablets 20pc', category: 'Household', image: 'https://placehold.co/100x100?text=Finish' },
    { id: 'hh-15', name: 'Tissue Paper Soft Roll 4pc', category: 'Household', image: 'https://placehold.co/100x100?text=Tissue' },
    { id: 'hh-16', name: 'Serviettes Napkins 100pc', category: 'Household', image: 'https://placehold.co/100x100?text=Serviettes' },
    { id: 'hh-17', name: 'Freshmax Air Freshener 300ml', category: 'Household', image: 'https://placehold.co/100x100?text=AirFresh' },
    { id: 'hh-18', name: 'Handy Andy Cleaner 750ml', category: 'Household', image: 'https://placehold.co/100x100?text=HandyAndy' },
    { id: 'hh-19', name: 'Scotch Brite Sponges 3pc', category: 'Household', image: 'https://placehold.co/100x100?text=ScotchBrite' },
    { id: 'hh-20', name: 'Doom Insect Killer 300ml', category: 'Household', image: 'https://placehold.co/100x100?text=Doom' },
];
